export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const DELETE_SELECTED_USER = 'DELETE_SELECTED_USER';
export const DISPLAY_SELECTED_USER_DETAILS = 'DISPLAY_SELECTED_USER_DETAILS';
export const GET_ALL_USERS_FAILURE = 'GET_ALL_USERS_FAILURE';
export const GET_USER_REPOS = 'GET_USER_REPOS';
export const GET_USER_REPOS_SUCCESS = 'GET_USER_REPOS_SUCCESS';
export const GET_USER_REPOS_FAILURE = 'GET_USER_REPOS_FAILURE';